name: quiz_app
description: A Quiz app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  equatable: ^2.0.5
  async: ^2.10.0  
  json_annotation: ^4.8.1
  logging: ^1.2.0
  dio: ^5.3.0
  retrofit: ^4.0.1
  drift: ^2.10.0
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.0.15
  path: ^1.8.2
  collection: ^1.18.0
  internet_connection_checker: ^1.0.0+1
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  pretty_dio_logger: ^1.3.1
  rxdart: ^0.28.0
  bloc_concurrency: ^0.2.2
  flutter_svg: ^2.0.7
  go_router: ^14.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  build_runner_core: ^7.2.10
  json_serializable: ^6.6.2
  retrofit_generator: ^8.1.0
  drift_dev: ^2.10.0
  mockito: ^5.4.2
  freezed: ^2.5.2
  http_mock_adapter: ^0.6.1
  bloc_test: ^9.1.3

flutter:
  uses-material-design: true
  generate: true
  assets: 
    - assets/icons/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en_US
  output_dir: lib/localization
  arb_dir: assets/localization

  


